### ISSUE TITLE
Improve drag and drop experience

### ISSUE THREAD

**Issue by Raathigesh** [Raathigesh/dazzle#1]
The drag and drop functionality to reorder the widgets. But it's not smooth enough. 

Should be improved to make the experience a lot better.

**Comment by jdiasamaro** [comment]
Hello,

Just to add to this topic: I have a layout that simply does not allow me to move widgets. As soon as I try it, browser will freeze and the "Aw, snap" page appears. Some info about the problem:

![image](https://user-images.githubusercontent.com/1225695/29022801-b2d49ddc-7b62-11e7-9c99-a53f864492af.png)

**Comment by Raathigesh** [comment]
Hello @jdiasamaro, Could you replicate the issue in a sample project and share it with me?
