### ISSUE TITLE
Plotly.js?

### ISSUE THREAD

**Issue by alexanderwhatley** [Raathigesh/dazzle#11]
In your example, you use charts.js to create the graphs. Does your library currently support plotly.js (https://plot.ly/javascript/)? I am asking because my current graphs come out blank when shown using your dashboard....

**Comment by Raathigesh** [comment]
Dazzle does not rely on any visualization library. It will render any react component you provide in a widget. If plot.ly works as a stand-alone component if your app, then it should work with dazzle too.

**Comment by alexanderwhatley** [comment]
I see. The graphs work fine on their own, and I made sure that the data is being passed correctly to the objects in the dashboard by printing out the data in the class constructor. Do you have any suggestions to debug why the graphs are not being rendered properly by the Dashboard?

**Comment by Raathigesh** [comment]
Would you be able to create a sample repo with the issue? I would be happy to take a look at it.

**Comment by alexanderwhatley** [comment]
I think I figured it out. The issue was that it looks like the DOM has to look for the graphs themselves to render, so in the render() function, I had to include both the dashboard as well as the JSX Plot elements themselves.

**Comment by Raathigesh** [comment]
Closing this for now. Feel free to re-open.
