### ISSUE TITLE
Custom Frame Suggestion 

### ISSUE THREAD

**Issue by adkel92** [Raathigesh/dazzle#14]
It would be good if there was a styles or background prop which you could pass to the custom frame. 

I'd quite like to create a metro themed dashboard with different background colors on the widgets

**Comment by Raathigesh** [comment]
Custom frame is a component that should be developed by you so you should be able to use any style you like. More detail on custom frame [here](https://github.com/Raathigesh/Dazzle/blob/master/docs/ImplementingACustomFrame.md). 

Let me know if I'm not understanding your requirement correctly!

**Comment by adamk5550** [comment]
Can you add additional props instead of the 4 currently supplied, e.g could i pass through a classNames prop to the custom frame ?

**Comment by Raathigesh** [comment]
I will look into it and get back to you!

**Comment by philmander** [comment]
This is workaround that might work for you:

You can already pass props to widgets. See https://github.com/Raathigesh/dazzle/pull/3 

```javascript
widgets: {
        AcademicProfile: {
          type: AcademicProfile,
          props: {
            bgColor: blue
          },
        },
      }
```

...and then you can access these in the widget frame via its `children` props:

```javascript
let { bgColor = 'gray' } = this.props.children.props;
```

**Comment by vlaurin** [comment]
I tried to make this a bit more straightforward in https://github.com/Raathigesh/dazzle/pull/44
