### ISSUE TITLE
How to pass parameters to the widget list components

### ISSUE THREAD

**Issue by n0trace** [Raathigesh/dazzle#18]
example:
```
widgets: {
                RecordPanel:{
                    type: ZcForm,
                    title: 'ZcForm',
                    props:{}
                },
        }
```
My component `RecordPanel` need props initialze state, have many `RecordPanel` ,How to pass different  props to different  RecordPanel

Look forward to your favourable reply,

**Comment by xavier630** [comment]
Have you taken a look at https://github.com/Raathigesh/dazzle/pull/3?
