### ISSUE TITLE
Resizing

### ISSUE THREAD

**Issue by krizka** [Raathigesh/Dazzle#2]
Can't find it in demo. Is it possible to resize rows/columns?

**Comment by Raathigesh** [comment]
Sorry! Resizing is not supported.

Maybe you could have multiple layouts and allow users to choose among those layouts?

**Comment by glebcha** [comment]
@Raathigesh but you can implement resize with class change of parent node (col-md-12 ---> col-md-11 etc.) or with style variables in jsx (40% ----> 39,8% etc.).

**Comment by max107** [comment]
> you can implement resize with class change of parent node

👍

**Comment by Raathigesh** [comment]
When multiple classes are provided (for different screen sizes like md, sm and xs), how to deal with them when resizing ?

[Angular Dashboard Framework's](http://angular-dashboard-framework.github.io/angular-dashboard-framework/#/sample/01) approch is presening user with a bunch of differnt layout. What's your thoughts on such an approach ?
