### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by AlessioVallero** [Raathigesh/dazzle#21]
With React 15.5, importing PropTypes from React is deprecated in favour of importing from the new 'prop-types' package.

Please substitute the following:
import React, { PropTypes } from 'react';
With:
import React from 'react';
import PropTypes from 'prop-types';

You obviously need to install the package prop-types

**Comment by awitherspoon** [comment]
[This](https://github.com/Raathigesh/dazzle/pull/23) should handle it, as well as prepare it for use after 16.0.0

**Comment by Raathigesh** [comment]
Thanks to @awitherspoon, this is now in master. Will do a release soon!

**Comment by hudochenkov** [comment]
@Raathigesh congratulations on relocation! 

Sorry for bothering. Would you be able to release new version with React 15.5+ support, please?

**Comment by Raathigesh** [comment]
Hey @hudochenkov 

Thank you and here is the release https://github.com/Raathigesh/dazzle/releases/tag/1.2.6.

Let me know if you run into any issues.
