### ISSUE TITLE
Using grid layout with resize

### ISSUE THREAD

**Issue by Jeevan-Kishore** [Raathigesh/dazzle#24]
Can we use this repo for the functionality of having a smooth drag drop functionality with grid sizing.

[](https://github.com/STRML/react-grid-layout)

**Comment by Raathigesh** [comment]
Dazzle meant to a dashboard framework. If you are looking for something more generic like a grid system, I would highly recommend looking into [react-grid-layout](https://github.com/STRML/react-grid-layout).
