### ISSUE TITLE
Update react-dnd

### ISSUE THREAD

**Issue by hudochenkov** [Raathigesh/dazzle#30]
There was so many hopes for 1.2.6 release that we won't see this warning anymore:

> Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

Unfortunatelly `react-dnd` and `react-dnd-html5-backend` are [pinned](https://github.com/Raathigesh/dazzle/blob/fb68d8a0eaad65895650d13ba96b11f80ec61e10/package.json#L87-L88) to old versions which wasn't aware about React 15.

Is there a reason why `react-dnd` and `react-dnd-html5-backend` are pinned to specific old version? Is it possible to use latest versions instead?

**Comment by Raathigesh** [comment]
I can't recall why but it should be alright to update to the latest version. I'll try to do it tomorrow!

**Comment by hudochenkov** [comment]
@Raathigesh Thank you very much!

**Comment by Raathigesh** [comment]
So here is the release https://github.com/Raathigesh/dazzle/releases/tag/1.2.7 with the updated react-dnd dependency. But I still see a warning pop up in the console in the example app but I did not have time to inspect whether it's from the core library or from some other utility. Let me know if you run into issues.

**Comment by hudochenkov** [comment]
It's fantastic! The warning is gone! Thank you very much!
