### ISSUE TITLE
Modifying props of widgets from Dashboard

### ISSUE THREAD

**Issue by c-lack** [Raathigesh/dazzle#38]
How would I go about altering the state of a widget from the dashboard component?
I have tried changing the dashboard state to give new props to the widget, and the dashboard state is successfully changed and re-rendered, but the state of the widget never changes.
Perhaps something similar to how props are passed to widgets, a ref could be created for each widget:
widget:{
    type: Widget,
    title: 'Widget',
    props: data,
    refs: 'child'
}
Thank you.

**Comment by bjclark13** [comment]
@c-lack did you ever find a solution for this? If so, I would be interested in knowing what you did. I am trying the same thing, as I want to persist the state of dynamic components within the widgets.

**Comment by c-lack** [comment]
Hi @bjclark13, 
Yes I found a solution. Within state.widgets, each widget has a props object. Updating this prop in the app component with setState will call componentWillRecieve props in the widget. When I posted this question I wasn't managing the state properly and so my widgets weren't receiving the new props.
