### ISSUE TITLE
React 16 support

### ISSUE THREAD

**Issue by akullpp** [Raathigesh/dazzle#40]
This project doesn't support React 16+ correct?

**Comment by Raathigesh** [comment]
The project is not updated to react 16. But react is marked as a peer dependency. Is there an issue you are seeing when you use it in a react 16 project?

**Comment by mathewthe2** [comment]
proptypes package is deprecated.

_Component DragDropContext(t) declared `PropTypes` instead of `propTypes`. Did you misspell the property assignment?_

**Comment by elhay-av** [comment]
when using this package with react 16, npm instal throw an error
```npm WARN react-dazzle@1.2.7 requires a peer of react@^0.14.0 || ^15.0.0-0 but none was installed.```

you only need to add ```"react": "^0.14.0 || ^15.0.0-0 || ^16.0.0"```
in peerDependencies section of package.json

Thank you

**Comment by olegkudriavtsev** [comment]
Hi, do you have any updates regarding this issue? I have a similar problem. Adding react and react-dom as peerDependency didn't resolve it. Do you have any thoughts how to fix it?

**Comment by pcross616** [comment]
this is now fixed in the pr #47 which has been merged @Raathigesh what do we need to do to get it published to npm.

**Comment by Raathigesh** [comment]
I'll do it tonight!

**Comment by Raathigesh** [comment]
Published master as [1.4.0](https://github.com/Raathigesh/dazzle/releases/tag/1.4.0). I mistakenly bumped the version to 1.4.0 instead of 1.3.0 but that should be fine.
