### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by Raathigesh** [Raathigesh/dazzle#41]
I'm looking for maintainers to keep an eye on this project and answer questions.  I don't use this project at the moment personally and I'm focused on few other projects, so I don't have the required time to answer questions, fix bugs and merge PRs.

If you are interested, please comment below.

**Comment by shannonlal** [comment]
I am interested in using this.  I experience recently taking over another small project and would be willing to give you a hand and eventually take this over if you still need help

**Comment by lacymorrow** [comment]
I'll help where I can.

**Comment by lalitaphalak** [comment]
We are using this in one of project, due to this I have added few minor customization(sending indexes back) but I would like you to give me access to this repository, so that I can contribute changes to your code as well which will help others to utilize this library.

**Comment by segebee** [comment]
@lalitaphalak have you converted this to react 16

**Comment by lalitaphalak** [comment]
@segebee No.

**Comment by Raathigesh** [comment]
Sorry for not responding on time. Thank you all coming forward to help on this. I'm added @lalitaphalak  as a collaborator for now. Hopefully, @lalitaphalak can help merge some open PRs and help others along the way.

**Comment by shilpikanade** [comment]
Is there a way to add an itemclick to a widget, so that when the widget is clicked, it launches a url or another page?

**Comment by danieldram** [comment]
I will try my best as I run into blockers while trying to use this as a foundation for a project I am working on. How quick are PR turn arounds in general?

**Comment by hugobarragon** [comment]
@Raathigesh @lalitaphalak  hello i will help maintain this project we use it has our main dashboards and  i am very excited with typescript V2
