### ISSUE TITLE
How to remove the webpack related matter in Dazzle 

### ISSUE THREAD

**Issue by AlluManikyam** [Raathigesh/dazzle#42]
I want to remove the web pack related matter and run as a general react project.what are the changes required if i changed to web pack to without web pack in react.

**Comment by Raathigesh** [comment]
What do you mean by general react project? What is the bundler you are going to use if you are not going to use webpack?

**Comment by AlluManikyam** [comment]
I am using the create-react-app, so it creates default bundler.I don't want the webpack bundler.could you please tell me what are the changes required if i removed web pack in dazzle.

**Comment by tripuracherukuri** [comment]
Yes, I across the same problem. How to use react-dazzle in create-react-app.

**Comment by Raathigesh** [comment]
Have you tried using this with create-react-app? There should not be any issue with it. What's the error you are encountering? Just install the npm package and require the CSS file.

**Comment by vlaurin** [comment]
@AlluManikyam @tripuracherukuri This repository is a library, it's not meant to be used as a seed for your own dashboards.

However, a repository that can used as seed is [Dazzle-Starter-Kit](https://github.com/Raathigesh/Dazzle-Starter-Kit) by the very same author.
It does use Webpack, but so does `create-react-app`.

If you still want to use Dazzle with `create-react-app`, it's perfectly fine and quite straightforward; here's an example: https://github.com/vlaurin/dazzle-bootstrap-seed

**Comment by Raathigesh** [comment]
Thanks @vlaurin. Closing this for now. Please reopen if required.
