### ISSUE TITLE
1.4.0 build causes "Uncaught TypeError: Super expression must either be null or a function, not undefined" error at runtime

### ISSUE THREAD

**Issue by denizoguz** [Raathigesh/dazzle#49]
This error only occurs when bundle is produced with production mode of webpack. **Keeping everything the same and rolling back to 1.2.7 fixes the issue.**

**Comment by pcross616** [comment]
A lot changed between 1.4.0 and 1.2.7 such as React 16+ and node v8+.  A stack trace and other information will help us understand your issue better than just one line and exception.

**Comment by denizoguz** [comment]
Since the build is minified there is no meaningful stack trace, and this error doesn't occur on non minified build. I understand that without a stack trace it is difficult to identify problem. I will try to give more information as much as I can. 
I have identified removing following line fixes the error but I need this method to add widgets on user action. It doesn't matter whether I'm calling the method or not, it always gives this error when loading bundle if it is imported. 

`import {addWidget} from 'react-dazzle';`

IntelliJ also highlights above statement and warns that "cannot resolve sysmbol addWidget"

here is the stack trace:
`
WorklogPRO_TimesheetBundle.js?locale=en-UK:32 Uncaught TypeError: Super expression must either be null or a function, not undefined
    at WorklogPRO_TimesheetBundle.js?locale=en-UK:32
    at WorklogPRO_TimesheetBundle.js?locale=en-UK:32
    at t.default (WorklogPRO_TimesheetBundle.js?locale=en-UK:32)
    at WorklogPRO_TimesheetBundle.js?locale=en-UK:32
    at Object.e.exports (WorklogPRO_TimesheetBundle.js?locale=en-UK:32)
    at n (WorklogPRO_TimesheetBundle.js?locale=en-UK:32)
    at Object.e.exports (WorklogPRO_TimesheetBundle.js?locale=en-UK:32)
    at n (WorklogPRO_TimesheetBundle.js?locale=en-UK:32)
    at Object.e.exports (WorklogPRO_TimesheetBundle.js?locale=en-UK:32)
    at n (WorklogPRO_TimesheetBundle.js?locale=en-UK:32)
`

**Comment by denizoguz** [comment]
@vlaurin, Thanks for trying it. You can close this issue for now. Project is huge and I don't want to attach all of it here. If I could replicate it in a small sized project, I will definitely upload it. For the time being I'm using 1.2.7. Thanks for your support.
