### ISSUE TITLE
Error on Bundle.js: "Super expression must either be null or a function, not defined"

### ISSUE THREAD

**Issue by lecontre** [Raathigesh/dazzle#51]
Currently Getting the following error in my bundle.js

The package runs perfectly in development mode but as soon as I build my bundle I get the following error:  "Super expression must either be null or a function, not defined"

Tracking the error takes to thi section in the lib.js 

`if("function"!=typeof t&&null!==t)throw new TypeError("Super expression must either be null or a function, not "+typeof t)`

*Note: Using React 16.3.2, webpack 4.8.4 and react-dazzle 1.4.0

**Comment by pcross616** [comment]
I need more information to help you with this.  All the test pass in both modes and I have a feeling it due to something else not dazzle. Feel free to re open with a repo.

**Comment by samsch** [comment]
I think the proper fix for this is to turn off uglification in this lib for the (package.json) main entrypoint `dist/lib.js`. A second minified UMD build could be provided as well, perhaps as `dist/react-dazzle.min.js`.

**Comment by pcross616** [comment]
I will look in to this further..

**Comment by shefali-kudos** [comment]
What was the solution for this?
