### ISSUE TITLE
Row Class should be on Columns parent

### ISSUE THREAD

**Issue by johncmckim** [Raathigesh/Dazzle#6]
I am trying to use Dazzle with [React Material Design Light](https://github.com/tleunen/react-mdl) but I am having issues with the grid structure. Dazzle generates the following html:

<img width="508" alt="html" src="https://cloud.githubusercontent.com/assets/1297227/18420726/d1bcd0ba-78bc-11e6-81e2-ac59d41f9492.png">

There is an extra div between `mdl-grid` and `mdl-cell`. React MDL uses flexbox. The extra div between the grid and the cells causes the cells to collapse.

<img width="426" alt="result" src="https://cloud.githubusercontent.com/assets/1297227/18420748/16844f7a-78bd-11e6-9f9e-a0ed31d045f2.png">

I've looked at the code. The reason the extra `<div />` is created in `Columns.js`. I assume it is there because React render requires a single element at the root. It seems to me that the `rowClass` should be on that div rather than in `Row.js`. 

IMO, `Row.js` is not really performing any useful task. The `rowClass` should be in `Columns.js` which makes `Row.js` redundant. I could be missing something though?

I would propose that `rowClass` is moved to `Columns.js` and `Row.js` is removed. `Columns.js` could even be renamed to `Row.js` if that makes more sense.

Thoughts? Happy to submit a PR if you want one.

**Comment by Raathigesh** [comment]
Hi,

> I would propose that rowClass is moved to Columns.js and Row.js is removed. Columns.js could even be renamed to Row.js if that makes more sense.

I agree with this proposal. Unfortunately, I won't be able to get to work on this immediately. If you are willing to send a PR, please do so. I will merge and push a release.

Let me know if I can help in anyway further.

**Comment by johncmckim** [comment]
I've sent a PR please let me know if I need to make any changes to it.

**Comment by Raathigesh** [comment]
Thank you for the awesome PR. Released with [v1.2.3](https://github.com/Raathigesh/Dazzle/releases/tag/v1.2.3). Let me know if you run into any further difficulty with dazzle.
