### ISSUE TITLE
Unable to get dashboard to render using npm install

### ISSUE THREAD

**Issue by aaronmagi** [Raathigesh/Dazzle#8]
Hi I tried using your example you have in the readme for "usage" after installing to my project with npm.  The problem is that the dashboard will not render.

I brought in some of you sample widgets to see if that was the issue but I still do not get anything to render using the sample you provided.

```
// Dashboard
const Dashboard = ('react-dazzle');

// Your widget
import BarChart from './widgets/BarChart';
import LineChart from './widgets/LineChart';
import DoughnutChart from './widgets/DoughnutChart';

// Default styles.
import 'react-dazzle/lib/style/style.css';

```

setting state...

``````
                            ```
widgets: {
                                        EngineTelemetricsWidget: {
                                  type: BarChart,
                                  title: 'Engine',
                                },
                                PerformanceWidget: {
                                  type: DoughnutChart,
                                  title: 'Reactor Temp',
                                },
                                ShipVitalTelemetricsWidget: {
                                  type: LineChart,
                                  title: 'Reactor Telemetrics',
                                },
                              },
                              llayout: {
                                rows: [{
                                  columns: [{
                                    className: 'col-md-12 col-sm-12 col-xs-12',
                                    widgets: [{key: 'ShipVitalTelemetricsWidget'}],
                                  }],
                                }, {
                                  columns: [{
                                    className: 'col-md-8 col-sm-8 col-xs-8',
                                    widgets: [{key: 'EngineTelemetricsWidget'}],
                                  }, {
                                    className: 'col-md-4 col-sm-4 col-xs-4',
                                    widgets: [{key: 'PerformanceWidget'}],
                                  }],
                                }],
                              }};
``````

```

(this is inside my render)


<div id="dashboard">
                    <Dashboard  widgets={this.state.widgets} layout={this.state.layout}  />
                </div>
```

**Comment by Raathigesh** [comment]
Hi,
Have you looked at [the starter kit project ](https://github.com/Raathigesh/Dazzle-Starter-Kit)of dazzle? It would be easy if you could provide a sample repo with your code so I can take a look at it.

**Comment by aaronmagi** [comment]
Yes I have looked at it.

I can not provide a sample repo as it is being integrated to a application at work.  Can you see any issues of what is shown above?

I can possibly move it into its own component as well and share that if its easier.

**Comment by Raathigesh** [comment]
I noticed a spelling mistake in the `layout` key of the state. You misspelled it as `llayout`. If this didn't solve the issue, It would be helpful If you could move it into its own component and share as a gist. 

I did not test with React 15.0.x but it should work. I will update the sample projects to React 15.0.x soon.

**Comment by Raathigesh** [comment]
> // Dashboard
> const Dashboard = ('react-dazzle');

And the `require` or `import from` keyword missing in the above snippet. Is it intentional ?

**Comment by aaronmagi** [comment]
Hey I ended up setting building it out into its own component and importing that into my app but ran into (intermediate value)[chartType] is not a function.  I havent had time to relook at it again, I saw a bunch of people taking about chart.js v2 not being supported currently by the older reactchart and when I tried to change it even using your package.json settings it still gave the same error.

**Comment by Raathigesh** [comment]
If you could add a sample hello world widget without react-chart, we can check whether react-dazzle is rendering the widgets as expected. Let me know how I can help you further.

**Comment by Raathigesh** [comment]
Hey @aaronmagi, do you still have problem with getting react-dazzle working ?
