### ISSUE TITLE
Unable to copy text in widgets to clipboard

### ISSUE THREAD

**Issue by cperera-aud** [Raathigesh/dazzle#9]
Hello,

I noticed that when a component is rendered as a widget in the dashboard text cannot be copied to a clipboard. I was wondering is this a limitation due to drag and drop. Please let me know if there are any workarounds or if I am missing anything!

Thanks in advance!

**Comment by Raathigesh** [comment]
React-DnD seems to be the one causing this. I will look into this.

**Comment by cperera-aud** [comment]
Hi Raathigesh,

I was wondering were you able to make any progress on this issue?

Thanks,
Chamira.

**Comment by Raathigesh** [comment]
I investigated but I couldn't find a proper solution yet. I should be able to dig more into this issue this weekend. Will get back to you soon.

**Comment by cperera-aud** [comment]
Thanks much appreciated!

**Comment by Raathigesh** [comment]
@cperera-aud  Sorry I could not finish the investigation of this issue. Are you still having trouble?

**Comment by cperera-aud** [comment]
@Raathigesh thank you for your reply. The issue is there however, its not a major issue on our end. It would be nice if it can be sorted out when you get some time.

**Comment by Raathigesh** [comment]
Fixed in [1.2.5](https://github.com/Raathigesh/dazzle/releases/tag/1.2.5)

**Comment by cperera-aud** [comment]
Thanks! Much appreciated!
